version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building INFERENCE Docker image
      - docker build -t gptoss20b-infer .
      - docker tag gptoss20b-infer:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gptoss20b-infer:latest
  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/gptoss20b-infer:latest
